apiVersion: v1
kind: Service
metadata:
  labels:
    app: pilot-hello-app
  name: pilot-hello-app-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pilot-hello-app
